[project]
name = "envninja"
version = "0.1.0"
description = "A lightweight environment variable manager and validator for Python 🥷"
authors = [
    { name = "Aswin Ganga", email = "your.email@example.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.7"
keywords = ["env", "dotenv", "config", "validator", "security", "python"]

dependencies = [
    "python-dotenv"
]

[project.urls]
"Homepage" = "https://github.com/Techy0Ganga/envninja.git"
"Source" = "https://github.com/Techy0Ganga/envninja.git"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["tests"]
